ignore_merge_commits = true
branch_whitelist = ["master", "release/*", "staging"]
pre_bump_hooks = [
    "npm version --no-git-tag-version --allow-same-version {{version}}"
]
post_bump_hooks = []
tag_prefix = "v"

[commit_types]
chore = { changelog_title = "Chore" }
ci = { changelog_title = "CI" }

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]
